# ASP.NET Core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- stage: Build
  jobs:
  - job: Build
    steps:

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'

  - stage: Deploy
    dependsOn: Build
    condition: suceeded()
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: Deploy
      steps:
      - task: Docker@2
      inputs:
        containerRegistry:
        repository:
        command: 'buildAndPush'
        Dockerfiler: 'Dockerfile'